import './globals.css'
import { ReactNode } from "react";

export const metadata = {
  title: '번역',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="en">
    <body>{children}</body>
    </html>
  )
}
