import './globals.css'
import { ReactNode } from "react";
import Recoil from "@/lib/recoil/Recoil";

export const metadata = {
  title: '번역',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="en">
    <Recoil>
      <body>{children}</body>
    </Recoil>
    </html>
  )
}
